/**
 * Route manifest — single source of truth for sitemap generation.
 *
 * Rules for page agents:
 * - DO NOT edit this file directly. A wiring agent adds routes after each page is built.
 * - priority: 1.0 = home, 0.9 = flagship SEO pages, 0.8 = dealer/city pages, 0.6 = supporting.
 * - changeFrequency: "daily" for price pages, "weekly" for location pages, "monthly" for static.
 */

export type SitemapRoute = {
  path: string;
  priority: number;
  changeFrequency:
    | "always"
    | "hourly"
    | "daily"
    | "weekly"
    | "monthly"
    | "yearly"
    | "never";
};

export const routes: SitemapRoute[] = [
  // ── Homepage ──────────────────────────────────────────────────────────────
  { path: "/", priority: 1.0, changeFrequency: "weekly" },

  // ── Flagship SEO pages (0.9) ──────────────────────────────────────────────
  { path: "/rungta-tmt-price-today", priority: 0.9, changeFrequency: "daily" },
  {
    path: "/rungta-tmt-dealer-delhi-ncr",
    priority: 0.9,
    changeFrequency: "monthly",
  },

  // ── Grade pages (0.8) ─────────────────────────────────────────────────────
  {
    path: "/rungta-fe-500d-tmt-bars",
    priority: 0.8,
    changeFrequency: "monthly",
  },
  {
    path: "/rungta-fe-550-tmt-bars",
    priority: 0.8,
    changeFrequency: "monthly",
  },

  // ── City pages (0.8) ──────────────────────────────────────────────────────
  {
    path: "/rungta-tmt-dealer-in-ghaziabad",
    priority: 0.8,
    changeFrequency: "weekly",
  },
  {
    path: "/rungta-tmt-dealer-in-noida",
    priority: 0.8,
    changeFrequency: "weekly",
  },
  {
    path: "/rungta-tmt-dealer-in-greater-noida",
    priority: 0.8,
    changeFrequency: "weekly",
  },
  {
    path: "/rungta-tmt-dealer-in-faridabad",
    priority: 0.8,
    changeFrequency: "weekly",
  },
  {
    path: "/rungta-tmt-dealer-in-gurgaon",
    priority: 0.8,
    changeFrequency: "weekly",
  },
  {
    path: "/rungta-tmt-dealer-in-meerut",
    priority: 0.8,
    changeFrequency: "weekly",
  },
  {
    path: "/rungta-tmt-dealer-in-moradabad",
    priority: 0.8,
    changeFrequency: "weekly",
  },
  {
    path: "/rungta-tmt-dealer-in-hapur",
    priority: 0.8,
    changeFrequency: "weekly",
  },

  // ── Article / guide pages (0.7) ───────────────────────────────────────────
  {
    path: "/bulk-tmt-bar-supplier-delhi-ncr",
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    path: "/tmt-bar-weight-chart",
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    path: "/tmt-steel-calculator",
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    path: "/fe-500-vs-fe-500d-vs-fe-550",
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    path: "/steel-required-for-1000-sq-ft-house",
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    path: "/rungta-steel-review",
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    path: "/rungta-tmt-specifications",
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    path: "/saria-rate-today-delhi",
    priority: 0.7,
    changeFrequency: "daily",
  },

  // ── Admin / noindex ───────────────────────────────────────────────────────
  { path: "/admin/rates", priority: 0.0, changeFrequency: "never" },
];
